### PR TITLE
Edit multiple bones

### PR DESCRIPTION
**Pull request by schroef**
This update has multiple updates as well as fixes

Added
- Functionality to edit multiple bones at once
- Preset save mechanism
- Quick bake button
- Continuous update for Animation Mode
- Show info to user in panel to go into Pose mode
- Documentation link in Preferences

Fixed
- Error when deactiving addon > wrong prop sb_collider change to sb_bone_collider

Changed
- UI to match Blender new panel design layout

> Preview adjust panel design

SpringBones-v091

### CODE REVIEW

**Comment by Roe-bit** [comment]
Ayyyy, cool!
What I would really like to see is multiple skeletons colliding with eachother on the same run. Is that possible?

**Comment by schroef** [comment]
> Ayyyy, cool! What I would really like to see is multiple skeletons colliding with eachother on the same run. Is that possible?

You mean in terms of editting the props or in the simulation modes?
I hardly know a thing about how the addon itself works. Its very complicated. I simply added functionality to the panel and to a couple properties.

**Comment by schroef** [comment]
Perhaps the bake function needs more work. I see the wiggle bones has a much more expanded operator for it.

**Comment by Roe-bit** [comment]
Let's yell at Artell then


HEY @artellblender HEY
PLEASE MAKE YOUR ADDON SYNC BETWEEN SKELETONS
THOUSANDS WOULD ENJOY THIS IF THAT WORKED
WE NEED EASIER PHYSICS SO BAD DUDE

**Comment by schroef** [comment]
> Let's yell at Artell then
> 
> HEY @artellblender HEY PLEASE MAKE YOUR ADDON SYNC BETWEEN SKELETONS THOUSANDS WOULD ENJOY THIS IF THAT WORKED WE NEED EASIER PHYSICS SO BAD DUDE

LEts get it working properly on a single one first. You request is perhaps a but to much now, also sounds very hard in terms of computing power

**Comment by artellblender** [comment]
Thanks for your work!

**Comment by artellblender** [comment]
Sorry I reverted the changes for safety since someone reported issues:
https://github.com/artellblender/springbones/pull/4
Actually, I think it would be best if  you create a fork/a new repo, and feel free to modify anything you want. Since I won't be maintaining or working much on this addon... Once you have done that I'll add a link to your work on the index page of SpringBone to notify users that another version of Spring Bones exists, ok?

**Comment by schroef** [comment]
I understand, i had not tested this under 3.0 or higher.

Could show a link or text with the error perhaps?

**Comment by schroef** [comment]
Sorry was on mobile and did notice the link, ive asked the user if i can test that scene he is showing.
Thing is, my edits did not alter live mode. I tried it first, but it caused issues and i kept that part out. So im not 100% sure what he shows i due to my edits.

**Comment by schroef** [comment]
I had a look at the issue. Im doubting this is due to my edits. I did not add anything to the interactive function because i noticed slow behavior when doing to much updates. As he show he's using interactive, its not due to my edits. Also he seems to be using the setup on a IK arm, is that even normal?
Ive asked him for the file and Blender version. Ive test a quick Rigify rig and didnt have any issue when using an IK arm with a spring bone in Interactive mode.

**Pull request merged**
